### ISSUE TITLE
Repository description is unclear

### ISSUE THREAD

**Issue by vi** [bm371613/refren#3]
> Facilitates refactoring/renaming 

Renaming what? Is it JavaScript-only or universal? Does it support refactoring Rust code?

**Comment by bm371613** [comment]
I'm not sure whether you don't know or want to point out how bad the description is :)

It processes text unaware of the language and unaware of what is actually being renamed (variables, constants..).

Would you say it would be covered if I added "language agnostic" and "code-style-aware"?

**Comment by vi** [comment]
What does it add to `sed -i`? Smart case and underscores handling? If yes, then description should mention text substitution and omit "refactoring".

**Comment by bm371613** [comment]
Refactoring is the intended use case that will guide future improvements. More specifically, the use case is renaming a concept in your code, like "noun phrase" to "term" or "http middleware" to "web component". That would require a series of sed commands or using refactor->rename (literally) feature of my IDE repeatedly.

A feature that makes sense for general substitution, but not refactoring, won't be implemented. Even if this project is not yet worthy of being called "refactoring tool", this is the direction.

**Comment by bm371613** [comment]
> A language agnostic, code-style aware, refactoring/renaming tool.

**Comment by vi** [comment]
It's better than current description.
